// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearDeploymentImageTagStmt, err = db.PrepareContext(ctx, clearDeploymentImageTag); err != nil {
		return nil, fmt.Errorf("error preparing query ClearDeploymentImageTag: %w", err)
	}
	if q.createAppStmt, err = db.PrepareContext(ctx, createApp); err != nil {
		return nil, fmt.Errorf("error preparing query CreateApp: %w", err)
	}
	if q.createDeploymentStmt, err = db.PrepareContext(ctx, createDeployment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDeployment: %w", err)
	}
	if q.createDomainStmt, err = db.PrepareContext(ctx, createDomain); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDomain: %w", err)
	}
	if q.createProjectStmt, err = db.PrepareContext(ctx, createProject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProject: %w", err)
	}
	if q.createServerStmt, err = db.PrepareContext(ctx, createServer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateServer: %w", err)
	}
	if q.createServiceStmt, err = db.PrepareContext(ctx, createService); err != nil {
		return nil, fmt.Errorf("error preparing query CreateService: %w", err)
	}
	if q.createTokenStmt, err = db.PrepareContext(ctx, createToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateToken: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteAppStmt, err = db.PrepareContext(ctx, deleteApp); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteApp: %w", err)
	}
	if q.deleteDomainStmt, err = db.PrepareContext(ctx, deleteDomain); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDomain: %w", err)
	}
	if q.deleteEnvVarStmt, err = db.PrepareContext(ctx, deleteEnvVar); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEnvVar: %w", err)
	}
	if q.deleteProjectStmt, err = db.PrepareContext(ctx, deleteProject); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProject: %w", err)
	}
	if q.deleteTokenStmt, err = db.PrepareContext(ctx, deleteToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteToken: %w", err)
	}
	if q.getAppStmt, err = db.PrepareContext(ctx, getApp); err != nil {
		return nil, fmt.Errorf("error preparing query GetApp: %w", err)
	}
	if q.getAppByWebhookIDStmt, err = db.PrepareContext(ctx, getAppByWebhookID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAppByWebhookID: %w", err)
	}
	if q.getDeploymentStmt, err = db.PrepareContext(ctx, getDeployment); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeployment: %w", err)
	}
	if q.getDomainStmt, err = db.PrepareContext(ctx, getDomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomain: %w", err)
	}
	if q.getDomainByHostnameStmt, err = db.PrepareContext(ctx, getDomainByHostname); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomainByHostname: %w", err)
	}
	if q.getProjectStmt, err = db.PrepareContext(ctx, getProject); err != nil {
		return nil, fmt.Errorf("error preparing query GetProject: %w", err)
	}
	if q.getServiceStmt, err = db.PrepareContext(ctx, getService); err != nil {
		return nil, fmt.Errorf("error preparing query GetService: %w", err)
	}
	if q.getTokenByHashStmt, err = db.PrepareContext(ctx, getTokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetTokenByHash: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.listAppsStmt, err = db.PrepareContext(ctx, listApps); err != nil {
		return nil, fmt.Errorf("error preparing query ListApps: %w", err)
	}
	if q.listAppsByProjectStmt, err = db.PrepareContext(ctx, listAppsByProject); err != nil {
		return nil, fmt.Errorf("error preparing query ListAppsByProject: %w", err)
	}
	if q.listDeploymentsByAppStmt, err = db.PrepareContext(ctx, listDeploymentsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeploymentsByApp: %w", err)
	}
	if q.listDomainsByAppStmt, err = db.PrepareContext(ctx, listDomainsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListDomainsByApp: %w", err)
	}
	if q.listEnvVarsByAppStmt, err = db.PrepareContext(ctx, listEnvVarsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListEnvVarsByApp: %w", err)
	}
	if q.listProjectsStmt, err = db.PrepareContext(ctx, listProjects); err != nil {
		return nil, fmt.Errorf("error preparing query ListProjects: %w", err)
	}
	if q.listServersStmt, err = db.PrepareContext(ctx, listServers); err != nil {
		return nil, fmt.Errorf("error preparing query ListServers: %w", err)
	}
	if q.listServicesStmt, err = db.PrepareContext(ctx, listServices); err != nil {
		return nil, fmt.Errorf("error preparing query ListServices: %w", err)
	}
	if q.listVerifiedProxyRoutesStmt, err = db.PrepareContext(ctx, listVerifiedProxyRoutes); err != nil {
		return nil, fmt.Errorf("error preparing query ListVerifiedProxyRoutes: %w", err)
	}
	if q.updateAppStmt, err = db.PrepareContext(ctx, updateApp); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateApp: %w", err)
	}
	if q.updateAppBuildTypeStmt, err = db.PrepareContext(ctx, updateAppBuildType); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAppBuildType: %w", err)
	}
	if q.updateAppInternalPortStmt, err = db.PrepareContext(ctx, updateAppInternalPort); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAppInternalPort: %w", err)
	}
	if q.updateAppStatusStmt, err = db.PrepareContext(ctx, updateAppStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAppStatus: %w", err)
	}
	if q.updateAppWebhookStmt, err = db.PrepareContext(ctx, updateAppWebhook); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAppWebhook: %w", err)
	}
	if q.updateDeploymentStatusStmt, err = db.PrepareContext(ctx, updateDeploymentStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeploymentStatus: %w", err)
	}
	if q.updateDomainVerifiedStmt, err = db.PrepareContext(ctx, updateDomainVerified); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDomainVerified: %w", err)
	}
	if q.updateProjectNameStmt, err = db.PrepareContext(ctx, updateProjectName); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProjectName: %w", err)
	}
	if q.updateServerStatusStmt, err = db.PrepareContext(ctx, updateServerStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateServerStatus: %w", err)
	}
	if q.upsertEnvVarStmt, err = db.PrepareContext(ctx, upsertEnvVar); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertEnvVar: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearDeploymentImageTagStmt != nil {
		if cerr := q.clearDeploymentImageTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearDeploymentImageTagStmt: %w", cerr)
		}
	}
	if q.createAppStmt != nil {
		if cerr := q.createAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAppStmt: %w", cerr)
		}
	}
	if q.createDeploymentStmt != nil {
		if cerr := q.createDeploymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeploymentStmt: %w", cerr)
		}
	}
	if q.createDomainStmt != nil {
		if cerr := q.createDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDomainStmt: %w", cerr)
		}
	}
	if q.createProjectStmt != nil {
		if cerr := q.createProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProjectStmt: %w", cerr)
		}
	}
	if q.createServerStmt != nil {
		if cerr := q.createServerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createServerStmt: %w", cerr)
		}
	}
	if q.createServiceStmt != nil {
		if cerr := q.createServiceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createServiceStmt: %w", cerr)
		}
	}
	if q.createTokenStmt != nil {
		if cerr := q.createTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTokenStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteAppStmt != nil {
		if cerr := q.deleteAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAppStmt: %w", cerr)
		}
	}
	if q.deleteDomainStmt != nil {
		if cerr := q.deleteDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDomainStmt: %w", cerr)
		}
	}
	if q.deleteEnvVarStmt != nil {
		if cerr := q.deleteEnvVarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEnvVarStmt: %w", cerr)
		}
	}
	if q.deleteProjectStmt != nil {
		if cerr := q.deleteProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProjectStmt: %w", cerr)
		}
	}
	if q.deleteTokenStmt != nil {
		if cerr := q.deleteTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTokenStmt: %w", cerr)
		}
	}
	if q.getAppStmt != nil {
		if cerr := q.getAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAppStmt: %w", cerr)
		}
	}
	if q.getAppByWebhookIDStmt != nil {
		if cerr := q.getAppByWebhookIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAppByWebhookIDStmt: %w", cerr)
		}
	}
	if q.getDeploymentStmt != nil {
		if cerr := q.getDeploymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeploymentStmt: %w", cerr)
		}
	}
	if q.getDomainStmt != nil {
		if cerr := q.getDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainStmt: %w", cerr)
		}
	}
	if q.getDomainByHostnameStmt != nil {
		if cerr := q.getDomainByHostnameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainByHostnameStmt: %w", cerr)
		}
	}
	if q.getProjectStmt != nil {
		if cerr := q.getProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectStmt: %w", cerr)
		}
	}
	if q.getServiceStmt != nil {
		if cerr := q.getServiceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getServiceStmt: %w", cerr)
		}
	}
	if q.getTokenByHashStmt != nil {
		if cerr := q.getTokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTokenByHashStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.listAppsStmt != nil {
		if cerr := q.listAppsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAppsStmt: %w", cerr)
		}
	}
	if q.listAppsByProjectStmt != nil {
		if cerr := q.listAppsByProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAppsByProjectStmt: %w", cerr)
		}
	}
	if q.listDeploymentsByAppStmt != nil {
		if cerr := q.listDeploymentsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeploymentsByAppStmt: %w", cerr)
		}
	}
	if q.listDomainsByAppStmt != nil {
		if cerr := q.listDomainsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDomainsByAppStmt: %w", cerr)
		}
	}
	if q.listEnvVarsByAppStmt != nil {
		if cerr := q.listEnvVarsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEnvVarsByAppStmt: %w", cerr)
		}
	}
	if q.listProjectsStmt != nil {
		if cerr := q.listProjectsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProjectsStmt: %w", cerr)
		}
	}
	if q.listServersStmt != nil {
		if cerr := q.listServersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listServersStmt: %w", cerr)
		}
	}
	if q.listServicesStmt != nil {
		if cerr := q.listServicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listServicesStmt: %w", cerr)
		}
	}
	if q.listVerifiedProxyRoutesStmt != nil {
		if cerr := q.listVerifiedProxyRoutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVerifiedProxyRoutesStmt: %w", cerr)
		}
	}
	if q.updateAppStmt != nil {
		if cerr := q.updateAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAppStmt: %w", cerr)
		}
	}
	if q.updateAppBuildTypeStmt != nil {
		if cerr := q.updateAppBuildTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAppBuildTypeStmt: %w", cerr)
		}
	}
	if q.updateAppInternalPortStmt != nil {
		if cerr := q.updateAppInternalPortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAppInternalPortStmt: %w", cerr)
		}
	}
	if q.updateAppStatusStmt != nil {
		if cerr := q.updateAppStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAppStatusStmt: %w", cerr)
		}
	}
	if q.updateAppWebhookStmt != nil {
		if cerr := q.updateAppWebhookStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAppWebhookStmt: %w", cerr)
		}
	}
	if q.updateDeploymentStatusStmt != nil {
		if cerr := q.updateDeploymentStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeploymentStatusStmt: %w", cerr)
		}
	}
	if q.updateDomainVerifiedStmt != nil {
		if cerr := q.updateDomainVerifiedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDomainVerifiedStmt: %w", cerr)
		}
	}
	if q.updateProjectNameStmt != nil {
		if cerr := q.updateProjectNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProjectNameStmt: %w", cerr)
		}
	}
	if q.updateServerStatusStmt != nil {
		if cerr := q.updateServerStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateServerStatusStmt: %w", cerr)
		}
	}
	if q.upsertEnvVarStmt != nil {
		if cerr := q.upsertEnvVarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertEnvVarStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	clearDeploymentImageTagStmt *sql.Stmt
	createAppStmt               *sql.Stmt
	createDeploymentStmt        *sql.Stmt
	createDomainStmt            *sql.Stmt
	createProjectStmt           *sql.Stmt
	createServerStmt            *sql.Stmt
	createServiceStmt           *sql.Stmt
	createTokenStmt             *sql.Stmt
	createUserStmt              *sql.Stmt
	deleteAppStmt               *sql.Stmt
	deleteDomainStmt            *sql.Stmt
	deleteEnvVarStmt            *sql.Stmt
	deleteProjectStmt           *sql.Stmt
	deleteTokenStmt             *sql.Stmt
	getAppStmt                  *sql.Stmt
	getAppByWebhookIDStmt       *sql.Stmt
	getDeploymentStmt           *sql.Stmt
	getDomainStmt               *sql.Stmt
	getDomainByHostnameStmt     *sql.Stmt
	getProjectStmt              *sql.Stmt
	getServiceStmt              *sql.Stmt
	getTokenByHashStmt          *sql.Stmt
	getUserByEmailStmt          *sql.Stmt
	listAppsStmt                *sql.Stmt
	listAppsByProjectStmt       *sql.Stmt
	listDeploymentsByAppStmt    *sql.Stmt
	listDomainsByAppStmt        *sql.Stmt
	listEnvVarsByAppStmt        *sql.Stmt
	listProjectsStmt            *sql.Stmt
	listServersStmt             *sql.Stmt
	listServicesStmt            *sql.Stmt
	listVerifiedProxyRoutesStmt *sql.Stmt
	updateAppStmt               *sql.Stmt
	updateAppBuildTypeStmt      *sql.Stmt
	updateAppInternalPortStmt   *sql.Stmt
	updateAppStatusStmt         *sql.Stmt
	updateAppWebhookStmt        *sql.Stmt
	updateDeploymentStatusStmt  *sql.Stmt
	updateDomainVerifiedStmt    *sql.Stmt
	updateProjectNameStmt       *sql.Stmt
	updateServerStatusStmt      *sql.Stmt
	upsertEnvVarStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		clearDeploymentImageTagStmt: q.clearDeploymentImageTagStmt,
		createAppStmt:               q.createAppStmt,
		createDeploymentStmt:        q.createDeploymentStmt,
		createDomainStmt:            q.createDomainStmt,
		createProjectStmt:           q.createProjectStmt,
		createServerStmt:            q.createServerStmt,
		createServiceStmt:           q.createServiceStmt,
		createTokenStmt:             q.createTokenStmt,
		createUserStmt:              q.createUserStmt,
		deleteAppStmt:               q.deleteAppStmt,
		deleteDomainStmt:            q.deleteDomainStmt,
		deleteEnvVarStmt:            q.deleteEnvVarStmt,
		deleteProjectStmt:           q.deleteProjectStmt,
		deleteTokenStmt:             q.deleteTokenStmt,
		getAppStmt:                  q.getAppStmt,
		getAppByWebhookIDStmt:       q.getAppByWebhookIDStmt,
		getDeploymentStmt:           q.getDeploymentStmt,
		getDomainStmt:               q.getDomainStmt,
		getDomainByHostnameStmt:     q.getDomainByHostnameStmt,
		getProjectStmt:              q.getProjectStmt,
		getServiceStmt:              q.getServiceStmt,
		getTokenByHashStmt:          q.getTokenByHashStmt,
		getUserByEmailStmt:          q.getUserByEmailStmt,
		listAppsStmt:                q.listAppsStmt,
		listAppsByProjectStmt:       q.listAppsByProjectStmt,
		listDeploymentsByAppStmt:    q.listDeploymentsByAppStmt,
		listDomainsByAppStmt:        q.listDomainsByAppStmt,
		listEnvVarsByAppStmt:        q.listEnvVarsByAppStmt,
		listProjectsStmt:            q.listProjectsStmt,
		listServersStmt:             q.listServersStmt,
		listServicesStmt:            q.listServicesStmt,
		listVerifiedProxyRoutesStmt: q.listVerifiedProxyRoutesStmt,
		updateAppStmt:               q.updateAppStmt,
		updateAppBuildTypeStmt:      q.updateAppBuildTypeStmt,
		updateAppInternalPortStmt:   q.updateAppInternalPortStmt,
		updateAppStatusStmt:         q.updateAppStatusStmt,
		updateAppWebhookStmt:        q.updateAppWebhookStmt,
		updateDeploymentStatusStmt:  q.updateDeploymentStatusStmt,
		updateDomainVerifiedStmt:    q.updateDomainVerifiedStmt,
		updateProjectNameStmt:       q.updateProjectNameStmt,
		updateServerStatusStmt:      q.updateServerStatusStmt,
		upsertEnvVarStmt:            q.upsertEnvVarStmt,
	}
}
