// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAppStmt, err = db.PrepareContext(ctx, createApp); err != nil {
		return nil, fmt.Errorf("error preparing query CreateApp: %w", err)
	}
	if q.createDeploymentStmt, err = db.PrepareContext(ctx, createDeployment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDeployment: %w", err)
	}
	if q.createDomainStmt, err = db.PrepareContext(ctx, createDomain); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDomain: %w", err)
	}
	if q.createProjectStmt, err = db.PrepareContext(ctx, createProject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProject: %w", err)
	}
	if q.createTokenStmt, err = db.PrepareContext(ctx, createToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateToken: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteAppStmt, err = db.PrepareContext(ctx, deleteApp); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteApp: %w", err)
	}
	if q.deleteDomainStmt, err = db.PrepareContext(ctx, deleteDomain); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDomain: %w", err)
	}
	if q.deleteEnvVarStmt, err = db.PrepareContext(ctx, deleteEnvVar); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEnvVar: %w", err)
	}
	if q.deleteProjectStmt, err = db.PrepareContext(ctx, deleteProject); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProject: %w", err)
	}
	if q.getAppStmt, err = db.PrepareContext(ctx, getApp); err != nil {
		return nil, fmt.Errorf("error preparing query GetApp: %w", err)
	}
	if q.getDeploymentStmt, err = db.PrepareContext(ctx, getDeployment); err != nil {
		return nil, fmt.Errorf("error preparing query GetDeployment: %w", err)
	}
	if q.getDomainByHostnameStmt, err = db.PrepareContext(ctx, getDomainByHostname); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomainByHostname: %w", err)
	}
	if q.getProjectStmt, err = db.PrepareContext(ctx, getProject); err != nil {
		return nil, fmt.Errorf("error preparing query GetProject: %w", err)
	}
	if q.getTokenByHashStmt, err = db.PrepareContext(ctx, getTokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetTokenByHash: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.listAppsStmt, err = db.PrepareContext(ctx, listApps); err != nil {
		return nil, fmt.Errorf("error preparing query ListApps: %w", err)
	}
	if q.listAppsByProjectStmt, err = db.PrepareContext(ctx, listAppsByProject); err != nil {
		return nil, fmt.Errorf("error preparing query ListAppsByProject: %w", err)
	}
	if q.listDeploymentsByAppStmt, err = db.PrepareContext(ctx, listDeploymentsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeploymentsByApp: %w", err)
	}
	if q.listDomainsByAppStmt, err = db.PrepareContext(ctx, listDomainsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListDomainsByApp: %w", err)
	}
	if q.listEnvVarsByAppStmt, err = db.PrepareContext(ctx, listEnvVarsByApp); err != nil {
		return nil, fmt.Errorf("error preparing query ListEnvVarsByApp: %w", err)
	}
	if q.listProjectsStmt, err = db.PrepareContext(ctx, listProjects); err != nil {
		return nil, fmt.Errorf("error preparing query ListProjects: %w", err)
	}
	if q.listVerifiedProxyRoutesStmt, err = db.PrepareContext(ctx, listVerifiedProxyRoutes); err != nil {
		return nil, fmt.Errorf("error preparing query ListVerifiedProxyRoutes: %w", err)
	}
	if q.updateAppStatusStmt, err = db.PrepareContext(ctx, updateAppStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAppStatus: %w", err)
	}
	if q.updateDeploymentStatusStmt, err = db.PrepareContext(ctx, updateDeploymentStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDeploymentStatus: %w", err)
	}
	if q.upsertEnvVarStmt, err = db.PrepareContext(ctx, upsertEnvVar); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertEnvVar: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAppStmt != nil {
		if cerr := q.createAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAppStmt: %w", cerr)
		}
	}
	if q.createDeploymentStmt != nil {
		if cerr := q.createDeploymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDeploymentStmt: %w", cerr)
		}
	}
	if q.createDomainStmt != nil {
		if cerr := q.createDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDomainStmt: %w", cerr)
		}
	}
	if q.createProjectStmt != nil {
		if cerr := q.createProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProjectStmt: %w", cerr)
		}
	}
	if q.createTokenStmt != nil {
		if cerr := q.createTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTokenStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteAppStmt != nil {
		if cerr := q.deleteAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAppStmt: %w", cerr)
		}
	}
	if q.deleteDomainStmt != nil {
		if cerr := q.deleteDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDomainStmt: %w", cerr)
		}
	}
	if q.deleteEnvVarStmt != nil {
		if cerr := q.deleteEnvVarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEnvVarStmt: %w", cerr)
		}
	}
	if q.deleteProjectStmt != nil {
		if cerr := q.deleteProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProjectStmt: %w", cerr)
		}
	}
	if q.getAppStmt != nil {
		if cerr := q.getAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAppStmt: %w", cerr)
		}
	}
	if q.getDeploymentStmt != nil {
		if cerr := q.getDeploymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDeploymentStmt: %w", cerr)
		}
	}
	if q.getDomainByHostnameStmt != nil {
		if cerr := q.getDomainByHostnameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainByHostnameStmt: %w", cerr)
		}
	}
	if q.getProjectStmt != nil {
		if cerr := q.getProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectStmt: %w", cerr)
		}
	}
	if q.getTokenByHashStmt != nil {
		if cerr := q.getTokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTokenByHashStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.listAppsStmt != nil {
		if cerr := q.listAppsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAppsStmt: %w", cerr)
		}
	}
	if q.listAppsByProjectStmt != nil {
		if cerr := q.listAppsByProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAppsByProjectStmt: %w", cerr)
		}
	}
	if q.listDeploymentsByAppStmt != nil {
		if cerr := q.listDeploymentsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeploymentsByAppStmt: %w", cerr)
		}
	}
	if q.listDomainsByAppStmt != nil {
		if cerr := q.listDomainsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDomainsByAppStmt: %w", cerr)
		}
	}
	if q.listEnvVarsByAppStmt != nil {
		if cerr := q.listEnvVarsByAppStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEnvVarsByAppStmt: %w", cerr)
		}
	}
	if q.listProjectsStmt != nil {
		if cerr := q.listProjectsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProjectsStmt: %w", cerr)
		}
	}
	if q.listVerifiedProxyRoutesStmt != nil {
		if cerr := q.listVerifiedProxyRoutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVerifiedProxyRoutesStmt: %w", cerr)
		}
	}
	if q.updateAppStatusStmt != nil {
		if cerr := q.updateAppStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAppStatusStmt: %w", cerr)
		}
	}
	if q.updateDeploymentStatusStmt != nil {
		if cerr := q.updateDeploymentStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDeploymentStatusStmt: %w", cerr)
		}
	}
	if q.upsertEnvVarStmt != nil {
		if cerr := q.upsertEnvVarStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertEnvVarStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	createAppStmt               *sql.Stmt
	createDeploymentStmt        *sql.Stmt
	createDomainStmt            *sql.Stmt
	createProjectStmt           *sql.Stmt
	createTokenStmt             *sql.Stmt
	createUserStmt              *sql.Stmt
	deleteAppStmt               *sql.Stmt
	deleteDomainStmt            *sql.Stmt
	deleteEnvVarStmt            *sql.Stmt
	deleteProjectStmt           *sql.Stmt
	getAppStmt                  *sql.Stmt
	getDeploymentStmt           *sql.Stmt
	getDomainByHostnameStmt     *sql.Stmt
	getProjectStmt              *sql.Stmt
	getTokenByHashStmt          *sql.Stmt
	getUserByEmailStmt          *sql.Stmt
	listAppsStmt                *sql.Stmt
	listAppsByProjectStmt       *sql.Stmt
	listDeploymentsByAppStmt    *sql.Stmt
	listDomainsByAppStmt        *sql.Stmt
	listEnvVarsByAppStmt        *sql.Stmt
	listProjectsStmt            *sql.Stmt
	listVerifiedProxyRoutesStmt *sql.Stmt
	updateAppStatusStmt         *sql.Stmt
	updateDeploymentStatusStmt  *sql.Stmt
	upsertEnvVarStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		createAppStmt:               q.createAppStmt,
		createDeploymentStmt:        q.createDeploymentStmt,
		createDomainStmt:            q.createDomainStmt,
		createProjectStmt:           q.createProjectStmt,
		createTokenStmt:             q.createTokenStmt,
		createUserStmt:              q.createUserStmt,
		deleteAppStmt:               q.deleteAppStmt,
		deleteDomainStmt:            q.deleteDomainStmt,
		deleteEnvVarStmt:            q.deleteEnvVarStmt,
		deleteProjectStmt:           q.deleteProjectStmt,
		getAppStmt:                  q.getAppStmt,
		getDeploymentStmt:           q.getDeploymentStmt,
		getDomainByHostnameStmt:     q.getDomainByHostnameStmt,
		getProjectStmt:              q.getProjectStmt,
		getTokenByHashStmt:          q.getTokenByHashStmt,
		getUserByEmailStmt:          q.getUserByEmailStmt,
		listAppsStmt:                q.listAppsStmt,
		listAppsByProjectStmt:       q.listAppsByProjectStmt,
		listDeploymentsByAppStmt:    q.listDeploymentsByAppStmt,
		listDomainsByAppStmt:        q.listDomainsByAppStmt,
		listEnvVarsByAppStmt:        q.listEnvVarsByAppStmt,
		listProjectsStmt:            q.listProjectsStmt,
		listVerifiedProxyRoutesStmt: q.listVerifiedProxyRoutesStmt,
		updateAppStatusStmt:         q.updateAppStatusStmt,
		updateDeploymentStatusStmt:  q.updateDeploymentStatusStmt,
		upsertEnvVarStmt:            q.upsertEnvVarStmt,
	}
}
