// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type App struct {
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	ServerID         string `json:"server_id"`
	Name             string `json:"name"`
	GitUrl           string `json:"git_url"`
	Branch           string `json:"branch"`
	BuildType        string `json:"build_type"`
	InternalPort     int64  `json:"internal_port"`
	Status           string `json:"status"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	AutoDeployBranch string `json:"auto_deploy_branch"`
	WebhookSecret    string `json:"webhook_secret"`
}

type Deployment struct {
	ID        string         `json:"id"`
	AppID     string         `json:"app_id"`
	Status    string         `json:"status"`
	Stage     string         `json:"stage"`
	BuildLog  string         `json:"build_log"`
	ImageTag  sql.NullString `json:"image_tag"`
	CreatedAt string         `json:"created_at"`
}

type Domain struct {
	ID        string `json:"id"`
	AppID     string `json:"app_id"`
	Hostname  string `json:"hostname"`
	Type      string `json:"type"`
	Verified  int64  `json:"verified"`
	CreatedAt string `json:"created_at"`
}

type EnvVar struct {
	AppID     string `json:"app_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	IsSecret  int64  `json:"is_secret"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Project struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Server struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Host      string         `json:"host"`
	SshKeyRef sql.NullString `json:"ssh_key_ref"`
	Status    string         `json:"status"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Service struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	ServerID         string         `json:"server_id"`
	TemplateSlug     string         `json:"template_slug"`
	Name             string         `json:"name"`
	Status           string         `json:"status"`
	GeneratedSecrets string         `json:"generated_secrets"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	InternalPort     int64          `json:"internal_port"`
	Exposed          int64          `json:"exposed"`
	Hostname         sql.NullString `json:"hostname"`
}

type Token struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Hash       string         `json:"hash"`
	Scopes     string         `json:"scopes"`
	CreatedAt  string         `json:"created_at"`
	LastUsedAt sql.NullString `json:"last_used_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
