// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const clearDeploymentImageTag = `-- name: ClearDeploymentImageTag :exec
update deployments
set image_tag = null
where id = ?
`

func (q *Queries) ClearDeploymentImageTag(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.clearDeploymentImageTagStmt, clearDeploymentImageTag, id)
	return err
}

const createApp = `-- name: CreateApp :one
insert into apps (
	id,
	project_id,
	server_id,
	name,
	git_url,
	branch,
	build_type,
	internal_port,
	status
)
values (?, ?, ?, ?, ?, ?, ?, ?, ?)
returning id, project_id, server_id, name, git_url, branch, build_type, internal_port, status, created_at, updated_at, auto_deploy_branch, webhook_secret
`

type CreateAppParams struct {
	ID           string `json:"id"`
	ProjectID    string `json:"project_id"`
	ServerID     string `json:"server_id"`
	Name         string `json:"name"`
	GitUrl       string `json:"git_url"`
	Branch       string `json:"branch"`
	BuildType    string `json:"build_type"`
	InternalPort int64  `json:"internal_port"`
	Status       string `json:"status"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.queryRow(ctx, q.createAppStmt, createApp,
		arg.ID,
		arg.ProjectID,
		arg.ServerID,
		arg.Name,
		arg.GitUrl,
		arg.Branch,
		arg.BuildType,
		arg.InternalPort,
		arg.Status,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServerID,
		&i.Name,
		&i.GitUrl,
		&i.Branch,
		&i.BuildType,
		&i.InternalPort,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoDeployBranch,
		&i.WebhookSecret,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
insert into deployments (id, app_id, status, stage, build_log, image_tag)
values (?, ?, ?, ?, ?, ?)
returning id, app_id, status, stage, build_log, image_tag, created_at
`

type CreateDeploymentParams struct {
	ID       string         `json:"id"`
	AppID    string         `json:"app_id"`
	Status   string         `json:"status"`
	Stage    string         `json:"stage"`
	BuildLog string         `json:"build_log"`
	ImageTag sql.NullString `json:"image_tag"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.queryRow(ctx, q.createDeploymentStmt, createDeployment,
		arg.ID,
		arg.AppID,
		arg.Status,
		arg.Stage,
		arg.BuildLog,
		arg.ImageTag,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Status,
		&i.Stage,
		&i.BuildLog,
		&i.ImageTag,
		&i.CreatedAt,
	)
	return i, err
}

const createDomain = `-- name: CreateDomain :one
insert into domains (id, app_id, hostname, type, verified)
values (?, ?, ?, ?, ?)
returning id, app_id, hostname, type, verified, created_at
`

type CreateDomainParams struct {
	ID       string `json:"id"`
	AppID    string `json:"app_id"`
	Hostname string `json:"hostname"`
	Type     string `json:"type"`
	Verified int64  `json:"verified"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.queryRow(ctx, q.createDomainStmt, createDomain,
		arg.ID,
		arg.AppID,
		arg.Hostname,
		arg.Type,
		arg.Verified,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Hostname,
		&i.Type,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
insert into projects (id, name)
values (?, ?)
returning id, name, created_at, updated_at
`

type CreateProjectParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.createProjectStmt, createProject, arg.ID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
insert into services (
	id,
	project_id,
	server_id,
	template_slug,
	name,
	status,
	generated_secrets,
	internal_port,
	exposed,
	hostname
)
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
returning id, project_id, server_id, template_slug, name, status, generated_secrets, internal_port, exposed, hostname, created_at, updated_at
`

type CreateServiceParams struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	ServerID         string         `json:"server_id"`
	TemplateSlug     string         `json:"template_slug"`
	Name             string         `json:"name"`
	Status           string         `json:"status"`
	GeneratedSecrets string         `json:"generated_secrets"`
	InternalPort     int64          `json:"internal_port"`
	Exposed          int64          `json:"exposed"`
	Hostname         sql.NullString `json:"hostname"`
}

type CreateServiceRow struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	ServerID         string         `json:"server_id"`
	TemplateSlug     string         `json:"template_slug"`
	Name             string         `json:"name"`
	Status           string         `json:"status"`
	GeneratedSecrets string         `json:"generated_secrets"`
	InternalPort     int64          `json:"internal_port"`
	Exposed          int64          `json:"exposed"`
	Hostname         sql.NullString `json:"hostname"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.queryRow(ctx, q.createServiceStmt, createService,
		arg.ID,
		arg.ProjectID,
		arg.ServerID,
		arg.TemplateSlug,
		arg.Name,
		arg.Status,
		arg.GeneratedSecrets,
		arg.InternalPort,
		arg.Exposed,
		arg.Hostname,
	)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServerID,
		&i.TemplateSlug,
		&i.Name,
		&i.Status,
		&i.GeneratedSecrets,
		&i.InternalPort,
		&i.Exposed,
		&i.Hostname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToken = `-- name: CreateToken :one
insert into tokens (id, name, hash, scopes)
values (?, ?, ?, ?)
returning id, name, hash, scopes, created_at, last_used_at
`

type CreateTokenParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Hash   string `json:"hash"`
	Scopes string `json:"scopes"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.queryRow(ctx, q.createTokenStmt, createToken,
		arg.ID,
		arg.Name,
		arg.Hash,
		arg.Scopes,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (id, email, password_hash)
values (?, ?, ?)
returning id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
delete from apps
where id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteAppStmt, deleteApp, id)
	return err
}

const deleteDomain = `-- name: DeleteDomain :exec
delete from domains
where id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteDomainStmt, deleteDomain, id)
	return err
}

const deleteEnvVar = `-- name: DeleteEnvVar :exec
delete from env_vars
where app_id = ? and key = ?
`

type DeleteEnvVarParams struct {
	AppID string `json:"app_id"`
	Key   string `json:"key"`
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.exec(ctx, q.deleteEnvVarStmt, deleteEnvVar, arg.AppID, arg.Key)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
delete from projects
where id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProjectStmt, deleteProject, id)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
delete from tokens
where id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTokenStmt, deleteToken, id)
	return err
}

const getApp = `-- name: GetApp :one
select id, project_id, server_id, name, git_url, branch, build_type, internal_port, status, created_at, updated_at, auto_deploy_branch, webhook_secret
from apps
where id = ?
`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.queryRow(ctx, q.getAppStmt, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServerID,
		&i.Name,
		&i.GitUrl,
		&i.Branch,
		&i.BuildType,
		&i.InternalPort,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoDeployBranch,
		&i.WebhookSecret,
	)
	return i, err
}

const getAppByWebhookID = `-- name: GetAppByWebhookID :one
select id, project_id, server_id, name, git_url, branch, build_type, internal_port, status, created_at, updated_at, auto_deploy_branch, webhook_secret
from apps
where id = ?
`

func (q *Queries) GetAppByWebhookID(ctx context.Context, id string) (App, error) {
	row := q.queryRow(ctx, q.getAppByWebhookIDStmt, getAppByWebhookID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServerID,
		&i.Name,
		&i.GitUrl,
		&i.Branch,
		&i.BuildType,
		&i.InternalPort,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoDeployBranch,
		&i.WebhookSecret,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
select id, app_id, status, stage, build_log, image_tag, created_at
from deployments
where id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.queryRow(ctx, q.getDeploymentStmt, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Status,
		&i.Stage,
		&i.BuildLog,
		&i.ImageTag,
		&i.CreatedAt,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
select id, app_id, hostname, type, verified, created_at
from domains
where id = ?
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.queryRow(ctx, q.getDomainStmt, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Hostname,
		&i.Type,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByHostname = `-- name: GetDomainByHostname :one
select id, app_id, hostname, type, verified, created_at
from domains
where hostname = ?
`

func (q *Queries) GetDomainByHostname(ctx context.Context, hostname string) (Domain, error) {
	row := q.queryRow(ctx, q.getDomainByHostnameStmt, getDomainByHostname, hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Hostname,
		&i.Type,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
select id, name, created_at, updated_at
from projects
where id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.queryRow(ctx, q.getProjectStmt, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
select id, project_id, server_id, template_slug, name, status, generated_secrets, internal_port, exposed, hostname, created_at, updated_at
from services
where id = ?
`

type GetServiceRow struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	ServerID         string         `json:"server_id"`
	TemplateSlug     string         `json:"template_slug"`
	Name             string         `json:"name"`
	Status           string         `json:"status"`
	GeneratedSecrets string         `json:"generated_secrets"`
	InternalPort     int64          `json:"internal_port"`
	Exposed          int64          `json:"exposed"`
	Hostname         sql.NullString `json:"hostname"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) GetService(ctx context.Context, id string) (GetServiceRow, error) {
	row := q.queryRow(ctx, q.getServiceStmt, getService, id)
	var i GetServiceRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServerID,
		&i.TemplateSlug,
		&i.Name,
		&i.Status,
		&i.GeneratedSecrets,
		&i.InternalPort,
		&i.Exposed,
		&i.Hostname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
select id, name, hash, scopes, created_at, last_used_at
from tokens
where hash = ?
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash string) (Token, error) {
	row := q.queryRow(ctx, q.getTokenByHashStmt, getTokenByHash, hash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, created_at, updated_at
from users
where email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApps = `-- name: ListApps :many
select id, project_id, server_id, name, git_url, branch, build_type, internal_port, status, created_at, updated_at, auto_deploy_branch, webhook_secret
from apps
order by created_at desc, name asc
`

func (q *Queries) ListApps(ctx context.Context) ([]App, error) {
	rows, err := q.query(ctx, q.listAppsStmt, listApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ServerID,
			&i.Name,
			&i.GitUrl,
			&i.Branch,
			&i.BuildType,
			&i.InternalPort,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoDeployBranch,
			&i.WebhookSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByProject = `-- name: ListAppsByProject :many
select id, project_id, server_id, name, git_url, branch, build_type, internal_port, status, created_at, updated_at, auto_deploy_branch, webhook_secret
from apps
where project_id = ?
order by created_at desc, name asc
`

func (q *Queries) ListAppsByProject(ctx context.Context, projectID string) ([]App, error) {
	rows, err := q.query(ctx, q.listAppsByProjectStmt, listAppsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ServerID,
			&i.Name,
			&i.GitUrl,
			&i.Branch,
			&i.BuildType,
			&i.InternalPort,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoDeployBranch,
			&i.WebhookSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByApp = `-- name: ListDeploymentsByApp :many
select id, app_id, status, stage, build_log, image_tag, created_at
from deployments
where app_id = ?
order by created_at desc, id desc
`

func (q *Queries) ListDeploymentsByApp(ctx context.Context, appID string) ([]Deployment, error) {
	rows, err := q.query(ctx, q.listDeploymentsByAppStmt, listDeploymentsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Status,
			&i.Stage,
			&i.BuildLog,
			&i.ImageTag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByApp = `-- name: ListDomainsByApp :many
select id, app_id, hostname, type, verified, created_at
from domains
where app_id = ?
order by created_at asc
`

func (q *Queries) ListDomainsByApp(ctx context.Context, appID string) ([]Domain, error) {
	rows, err := q.query(ctx, q.listDomainsByAppStmt, listDomainsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Hostname,
			&i.Type,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVarsByApp = `-- name: ListEnvVarsByApp :many
select app_id, key, value, is_secret, created_at, updated_at
from env_vars
where app_id = ?
order by key asc
`

func (q *Queries) ListEnvVarsByApp(ctx context.Context, appID string) ([]EnvVar, error) {
	rows, err := q.query(ctx, q.listEnvVarsByAppStmt, listEnvVarsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVar
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.AppID,
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
select id, name, created_at, updated_at
from projects
order by created_at desc, name asc
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsStmt, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
select id, project_id, server_id, template_slug, name, status, generated_secrets, internal_port, exposed, hostname, created_at, updated_at
from services
order by created_at desc, name asc
`

type ListServicesRow struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	ServerID         string         `json:"server_id"`
	TemplateSlug     string         `json:"template_slug"`
	Name             string         `json:"name"`
	Status           string         `json:"status"`
	GeneratedSecrets string         `json:"generated_secrets"`
	InternalPort     int64          `json:"internal_port"`
	Exposed          int64          `json:"exposed"`
	Hostname         sql.NullString `json:"hostname"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.query(ctx, q.listServicesStmt, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ServerID,
			&i.TemplateSlug,
			&i.Name,
			&i.Status,
			&i.GeneratedSecrets,
			&i.InternalPort,
			&i.Exposed,
			&i.Hostname,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedProxyRoutes = `-- name: ListVerifiedProxyRoutes :many
select domains.hostname, 'app' as target_type, apps.id as target_id, apps.internal_port
from domains
join apps on apps.id = domains.app_id
where domains.verified = 1
union all
select services.hostname, 'service' as target_type, services.id as target_id, services.internal_port
from services
where services.exposed = 1 and services.hostname is not null and services.hostname <> ''
order by hostname asc
`

type ListVerifiedProxyRoutesRow struct {
	Hostname     string `json:"hostname"`
	TargetType   string `json:"target_type"`
	TargetID     string `json:"target_id"`
	InternalPort int64  `json:"internal_port"`
}

func (q *Queries) ListVerifiedProxyRoutes(ctx context.Context) ([]ListVerifiedProxyRoutesRow, error) {
	rows, err := q.query(ctx, q.listVerifiedProxyRoutesStmt, listVerifiedProxyRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedProxyRoutesRow
	for rows.Next() {
		var i ListVerifiedProxyRoutesRow
		if err := rows.Scan(
			&i.Hostname,
			&i.TargetType,
			&i.TargetID,
			&i.InternalPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :one
update apps
set
	name = ?,
	git_url = ?,
	branch = ?,
	build_type = ?,
	internal_port = ?,
	updated_at = current_timestamp
where id = ?
returning id, project_id, server_id, name, git_url, branch, build_type, internal_port, status, created_at, updated_at, auto_deploy_branch, webhook_secret
`

type UpdateAppParams struct {
	Name         string `json:"name"`
	GitUrl       string `json:"git_url"`
	Branch       string `json:"branch"`
	BuildType    string `json:"build_type"`
	InternalPort int64  `json:"internal_port"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error) {
	row := q.queryRow(ctx, q.updateAppStmt, updateApp,
		arg.Name,
		arg.GitUrl,
		arg.Branch,
		arg.BuildType,
		arg.InternalPort,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServerID,
		&i.Name,
		&i.GitUrl,
		&i.Branch,
		&i.BuildType,
		&i.InternalPort,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoDeployBranch,
		&i.WebhookSecret,
	)
	return i, err
}

const updateAppBuildType = `-- name: UpdateAppBuildType :exec
update apps
set build_type = ?, updated_at = current_timestamp
where id = ?
`

type UpdateAppBuildTypeParams struct {
	BuildType string `json:"build_type"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateAppBuildType(ctx context.Context, arg UpdateAppBuildTypeParams) error {
	_, err := q.exec(ctx, q.updateAppBuildTypeStmt, updateAppBuildType, arg.BuildType, arg.ID)
	return err
}

const updateAppInternalPort = `-- name: UpdateAppInternalPort :exec
update apps
set internal_port = ?, updated_at = current_timestamp
where id = ?
`

type UpdateAppInternalPortParams struct {
	InternalPort int64  `json:"internal_port"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateAppInternalPort(ctx context.Context, arg UpdateAppInternalPortParams) error {
	_, err := q.exec(ctx, q.updateAppInternalPortStmt, updateAppInternalPort, arg.InternalPort, arg.ID)
	return err
}

const updateAppStatus = `-- name: UpdateAppStatus :exec
update apps
set status = ?, updated_at = current_timestamp
where id = ?
`

type UpdateAppStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAppStatus(ctx context.Context, arg UpdateAppStatusParams) error {
	_, err := q.exec(ctx, q.updateAppStatusStmt, updateAppStatus, arg.Status, arg.ID)
	return err
}

const updateAppWebhook = `-- name: UpdateAppWebhook :one
update apps
set auto_deploy_branch = ?, webhook_secret = ?, updated_at = current_timestamp
where id = ?
returning id, project_id, server_id, name, git_url, branch, build_type, internal_port, status, created_at, updated_at, auto_deploy_branch, webhook_secret
`

type UpdateAppWebhookParams struct {
	AutoDeployBranch string `json:"auto_deploy_branch"`
	WebhookSecret    string `json:"webhook_secret"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateAppWebhook(ctx context.Context, arg UpdateAppWebhookParams) (App, error) {
	row := q.queryRow(ctx, q.updateAppWebhookStmt, updateAppWebhook, arg.AutoDeployBranch, arg.WebhookSecret, arg.ID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ServerID,
		&i.Name,
		&i.GitUrl,
		&i.Branch,
		&i.BuildType,
		&i.InternalPort,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoDeployBranch,
		&i.WebhookSecret,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
update deployments
set status = ?, stage = ?, build_log = ?, image_tag = ?
where id = ?
`

type UpdateDeploymentStatusParams struct {
	Status   string         `json:"status"`
	Stage    string         `json:"stage"`
	BuildLog string         `json:"build_log"`
	ImageTag sql.NullString `json:"image_tag"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.exec(ctx, q.updateDeploymentStatusStmt, updateDeploymentStatus,
		arg.Status,
		arg.Stage,
		arg.BuildLog,
		arg.ImageTag,
		arg.ID,
	)
	return err
}

const updateDomainVerified = `-- name: UpdateDomainVerified :one
update domains
set verified = ?
where id = ?
returning id, app_id, hostname, type, verified, created_at
`

type UpdateDomainVerifiedParams struct {
	Verified int64  `json:"verified"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateDomainVerified(ctx context.Context, arg UpdateDomainVerifiedParams) (Domain, error) {
	row := q.queryRow(ctx, q.updateDomainVerifiedStmt, updateDomainVerified, arg.Verified, arg.ID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Hostname,
		&i.Type,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectName = `-- name: UpdateProjectName :one
update projects
set name = ?, updated_at = current_timestamp
where id = ?
returning id, name, created_at, updated_at
`

type UpdateProjectNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error) {
	row := q.queryRow(ctx, q.updateProjectNameStmt, updateProjectName, arg.Name, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEnvVar = `-- name: UpsertEnvVar :one
insert into env_vars (app_id, key, value, is_secret)
values (?, ?, ?, ?)
on conflict(app_id, key) do update set
	value = excluded.value,
	is_secret = excluded.is_secret,
	updated_at = current_timestamp
returning app_id, key, value, is_secret, created_at, updated_at
`

type UpsertEnvVarParams struct {
	AppID    string `json:"app_id"`
	Key      string `json:"key"`
	Value    string `json:"value"`
	IsSecret int64  `json:"is_secret"`
}

func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) (EnvVar, error) {
	row := q.queryRow(ctx, q.upsertEnvVarStmt, upsertEnvVar,
		arg.AppID,
		arg.Key,
		arg.Value,
		arg.IsSecret,
	)
	var i EnvVar
	err := row.Scan(
		&i.AppID,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
